project 'LGBarCharts.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'LGBarCharts' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  # Pods for LGBarCharts

  target 'LGBarChartsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LGBarChartsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
